version: "3.8"

services:
  similarity:
    build: ./similarity_service
    container_name: similarity
    ports:
      - "5001:5001"
    networks:
      - ssnet

  db:
    image: postgres:15
    container_name: summer-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitirmedb
    ports:
      - "5432:5432"
    networks:
      - ssnet

  web:
    build: .
    container_name: summer
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bitirmedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SIMILARITY_API_URL: http://similarity:5001/similarity
    depends_on:
      - similarity
      - db
    networks:
      - ssnet

networks:
  ssnet:
    driver: bridge
