--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: home_course; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (6, 2, 3, 2, 'İş Sağlığı ve Güvenliği Esasları ve Laboratuvarda Uyulması Gereken Kurallar | Birim sistemleri ve Vektörler | Bir Boyutta Hareket | İki Boyutta Hareket | Newton’un Hareket Yasaları | Newton’un Hareket Yasalarının Uygulamaları | İş ve Kinetik Enerji | Potansiyel Enerji ve Mekanik Enerjinin Korunumu | Uygulama | Doğrusal Momentum ve Çarpışmalar | Statik Denge ve Moment | Katı Cisimlerin Dönme Hareketi | Katı Cisimlerin Dönme Hareketi | Maddenin Özellikleri', 'Physıcs I', 'FIRST', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (6, 0, 4, 3, 'Kümeler. Sayı Kümeleri. Denklemler. Özdeşlikler. Eşitsizlikler. | Fonksiyon kavramı. Fonksiyon çeşitler (Polinom fonksiyon, rasyonel fonksiyon, köklü fonksiyon, üstel ve logaritma fonksiyonu ve bu fonksiyonların en geniş tanım kümeleri). | Fonksiyon çeşitleri (Trigonometrik, ters trigonometrik ve hiperbolik fonksiyonlar.) Parçalı fonksiyonlar, özel tanımlı (Mutlak değer, tam değer, işaret) fonksiyonları. | Limit kavramı ve limit tanımı ile limit hesabı. Limit hesabı için kullanılan teoremlerin ispatı. Sandviç teoremi. Trigonometrik fonksiyonların limitleri. | Sağ ve sol taraflı limitler. Belirsiz haller (0/0,sonsuz/sonsuz, 0.sonsuz, sonsuz-sonsuz,1^sonsuz). | Fonksiyonlarda süreklilik kavramı. Süreksizlik çeşitleri. Sürekli fonksiyonların özellikleri (maksimum ve minimum degerler.) | Türev kavramı ve türev tanımı ile türev hesabı. Türev tanımı ile türev alma kurallarının ispatı. Ters fonksiyonun türevi. | Trigonometrik ve ters trigonometrik fonksiyonların türevi. Üstel ve logaritma fonksiyonlarının türevi. Hiperbolik ve ters hiperbolik fonksiyonların türevi.Parametrik denklemleri verilen fonksiyonların türevleri. Kapalı fonksiyonların türevi. | Yüksek mertebeden türev. Leibniz kuralı ile yüksek mertebeden türev. Kapalı Türev. | Teğet ve normal denklemi. | Artan ve azalan fonksiyonlar. Belirsiz Haller (L’Hopital Kuralı ile incelenmesi). | Fonksiyonların maksimum ve minimumu, asimptotlar. | Eğri çizimleri. | Diferansiyel ile yaklaşık hesap. Maksimum minimum problemleri. Mühendislik problemleri.', 'Mathematıcs I', 'FIRST', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 3, 4, 'Lineer denklem sistemlerine giriş | Vektor denklemleri. Ax=b matrix sistemleri. Eselon ve satıra eselon formlar. | Gauss ve Gauss-Jordan Yok Etme Metodları. | Matrislerde islemler ve islemlerin özellikleri. | Lineer sistemler teorisi, homojen ve homojen olmayan sistemler, rank. | Bir matrisin tersi ve terslenebilir matrislerin karakterizasyonu. | LU ayrisimi. Bir matrisin determinanti. Determinant ve elementer satir/sutun islemleri. Determinantin özellikleri. | Determinantin uygulamalari ve Cramer''s kuralı. | Vektorler, lineer bagimsizlik, taban ve donusumler. | Skaler carpim, orthonormal tabanlar, Gram-Schmidt Metodu, QR ayrisimi. | Ozdegerler ve ozvektorler | Karakteristik polinom ve Cayley-Hamilton Teoremi. | Benzer matrisler ve kosegenlestirme. | Lineer sistemlerin davranislari ve özdeğerler/ozvektorler.', 'Lineer Cebir', 'FIRST', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 2, 2, 5, 'Ders Tanıtımı & Giriş | Yazılım Mühendisliği Yaşam Döngüsü ve Algoritma Kavramı | Algoritma ve Sözde Kod Yazma | Akış Diyagramı | Programlama ve Programlama Dili Kavramı | Yapısal Programlama Kavramı | Değişken Kavramı, Karar Yapıları, İterasyonlar, Döngüler | Yıl İçi Sınavı | Diziler (Sayı ve Karakter Dizileri) | Alt Yordam Kavramı | Alt Yordam Kavramı | İşaretçiler ve Dinamik Hafıza Yönetimi | Nesneye Dayalı Programlama | Dosyalarda Giriş/Çıkış İşlemleri', 'Yazılım Mühendisliğinde Problem Çözümleme', 'FIRST', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 6, 'Bölümün ve yazılım mühendisliğinin tanıtımı, oryantasyon. | Bilgisayarın donanımsal yapısı ve yazılım. Programlama temelleri, yazılım yaşam döngüsü. | Programlama dilleri ve program geliştirme ortamları: Editörler, derleyiciler ve hata ayıklayıcılar. | Versiyon kontrol sistemleri: GIT. | Algoritmalar. | Yazılım mühendisliğinde etik değerler. | İşletim sistemleri ve bilgisayar ağları. | Sorgu dilleri ve veri tabanı sistemleri. | Görü temelli sistemler, görüntü işleme. | Web tabanlı dağıtık bilgi sistemleri. | Web ve mobil uygulama geliştirme platformları, örnek uygulamalar. | Büyük veri ve yapay zeka. | Yazılım geliştirme süreç yönetim temelleri (DevOps). | Örnek yazılım sistemlerinin veya uygulamaların sunumları.', 'Yazılım Mühendisliğine Giriş', 'FIRST', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 4, 7, ' |  |  |  |  |  |  |  |  |  |  |  |  | ', 'Yabancı Dil', 'FIRST', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (6, 2, 3, 8, 'Laboratuvarda Uyulması Gereken Kurallar ile İş Sağlığı ve Güvenliği Esasları | Coulomb Yasası ve Elektriksel Kuvvet | Elektrik Alanı ve Gauss Yasası | Elektriksel Potansiyel | Sığa ve Kondansatörler, Dielektriklerin Özellikleri | Akım ve Direnç | Doğru Akım Devreleri | Elektromanyetik Kuvvet | Manyetik Alan Kaynakları | Uygulama | Elektromanyetik İndüksiyon, Faraday Yasası | Elektromanyetik İndüksiyon, Özindüksiyon | Alternatif Akım Devreleri (RL ve RC Devreleri) | Elektromanyetik Dalgalar', 'Physıcs II', 'FIRST', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 3, 20, 'Giriş, Dil Tasarımı Kavramları | Programlama Dillerin Tarihçesi | Sözdizimi ve Semantiği Tanımlama | Sözlüksel ve Sözdizimi Analizi | Adlar, Bağlantılar ve Kapsam | İsim uzayı ve veri tipleri | İfadeler ve Atama İfadeleri | İfade Düzeyinde Kontrol Yapıları | Alt Programlar | Soyut Veri Tipleri ve Kapsülleme Yapısı | Nesneye Yönelik Programlama | Programlama dillerinde hata yakalama | Programlama dillerinde eşzamanlılık | Yorumlamalı Diller ve Python', 'Programlama Dillerinin Prensipleri', 'SECOND', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (6, 0, 4, 9, 'Belirsiz integral. Belirsiz integral alma kuralları. Değişken değiştirme yöntemi. | Kısmi integrasyon yöntemi. Rasyonel fonksiyonların integrali. | Trigonometrik ifadelerin integrali. Trigonometrik dönüşümler. | Binom integrali. Çeşitli değişken değiştirmeler. | Belirli integral kavramı. Aralığın bölüntüsü, Riemann toplamı ve belirli integral tanımı. | Belirli integralin tanım kullanılarak hesabı. Temel integral alma kurallarının ispatı. | İntegral hesabının temel teoremleri. Belirli integralde değişken değiştirme yöntemi. | Belirli integralde kısmi integrasyon yöntemi. Bazı özel tanımlı fonksiyonların belirli integrali. | Belirli integral kullanarak alan hesabı. | Belirli integral kullanarak hacim hesabı. Disk metodu. | Belirli integral kullanarak hacim hesabı. Silindirik tabakalar metodu. | Eğri yayının uzunluğu. Dönel cisimlerin yüzey alanı. | Has Olmayan (Genelleştirilmiş) integraller. | Has Olmayan integral yardımı ile alan ve hacim hesabı.', 'Mathematıcs II', 'FIRST', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 3, 10, 'Dersin tanıtımı | Giriş, istatistik, tanımlar ve konseptler | Açıklayıcı istatistikler | Açıklayıcı istatistikler | Olasılık, tanımlar, özellikler, istatistiksel önem | Olasılık, tanımlar, özellikler, istatistiksel önem | Olasılık dağılımları | Olasılık dağılımları | Örnekler | Basit doğrusal regresyon | Çoklu doğrusal regresyon | Hipotez testleri | Hipotez testleri | Değişkenlik analizi', 'Olasılık ve İstatistik', 'FIRST', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 11, 'Ders Tanıtımı & Giriş | Nesneye Dayalı Programlama Kavramına Giriş | Nesneye Dayalı Programlama Kavramına Giriş | Kontrol İfadeleri, Döngüler ve Fonksiyonlar | Sınıf, Erişim Denetleyicisi, Üye Değişken ve Fonksiyonlar | Sınıf, Erişim Denetleyicisi, Üye Değişken ve Fonksiyonlar | Kalıtım, Çoklu Kalıtım ve Arayüzler | Kalıtım, Çoklu Kalıtım ve Arayüzler | Çoklu Kalıtım ve Kapsülleme | Çoklu Kalıtım ve Kapsülleme | Statik Üye Değişken ve Fonksiyon | Const Sınıf Nesneleri, Üye Değişken ve Fonksiyonlar | UML, UML Sınıf Diyagramları, UML Kullanıcı Diyagramları | UML, UML Sınıf Diyagramları, UML Kullanıcı Diyagramları', 'Nesne Yönelimli Programlama', 'FIRST', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 12, 'Ders Tanıtımı ve Giriş | Kullanıcı Arayüzü Gereklilikleri - Kullanılabilirlik, Öğrenilebilirlik | Kullanıcı Arayüzü Gereklilikleri - Verimlilik | Kullanıcı Arayüzü Gereklilikleri - Renk Tasarımı ve Tipografi | Kullanıcı Arayüzü Gereklilikleri - Erişilebilirlik, Özümseme | Giriş-Çıkış Teknolojisi | Görev Analizi | Kullanıcı-Kontrollü Tasarım | Arayüz Değerlendirme | Deneysel Analiz | Deneysel Test | Heuristik Değerlendirme | Kullanıcı Kontrolü ve Test Etme | Kullanıcı Kontrolü ve Test Etme', 'Kullanıcı Arayüz Tasarımı ve Testi', 'FIRST', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 4, 13, 'Atatürk İlkeleri ve İnkılap Tarihinin içeriği ve amacı - Yenilik ve benzeri kavramlar | Osmanlı Devletinin yapısı ve çözülme sebepleri - Devleti kurtarma ve reform çabaları | Osmanlı Devlet''inde Meşruti gelişmeler ve entelektüel hareketler - Osmanlı Devletinin jeopolitiği ve ona karşı dış politika | İttihat ve Terakki Partisi´nin yönetimi ve devletin son aşaması - 1. Dünya Savaşı ve Osmanlı Devleti | Mondros Mütarekesi ve ona bağlı işgaller, Osmanlı''dan toprak istekleri ve Paris Barış Konferansı - Türk milletinin bağımsızlık için kararlılığı ve Mustafa Kemal Paşa | Mustafa Kemal Paşa''nın fikirleri ve Anadolu''ya geçişi - Kongreler Dönemi (Amasya Görüşmesi, Erzurum ve Sivas Kongreleri) | İstanbul''un İşgali, Türk halkının tepkisi ve diğer önemli gelişmeler - Türkiye Büyük Millet Meclisi''nin açılışı ve özellikleri | Meclisin ilk faaliyetleri ve ilk kanunlar - Meclise tepkiler, dahili isyanlar, karşıt topluluklar, Milli mücadelede basın | ARA SINAV | Milli Mücadelede cepheler, güney ve güneydoğu cephesi - Milli Mücadelede cepheler, doğu cephesi ve Ermeni sorunu | Milli Mücadelede cepheler, Batı cephesi, İlk işgaller ve milli ordular - Düzenli ordunun kuruluşu ve milli mücadelenin finansal kaynakları | Sevr Anlaşması ve Türk milleti üzerindeki etkisi - Milli Mücadelede cepheler, İnönü I, İnönü II, Sakarya Savaşları ve Büyük Taarruz | Milli Mücadelenin siyasi tarafı, Mudanya Ateşkesi ve Lozan Barış Anlaşması, Atatürk dönemi Türk dış politikası - Siyaset, eğitim, kültür, hukuk ve sosyal alanlarda devrimler | Atatürk İlkeleri (Cumhuriyetçilik, Milliyetçilik, Halkçılık) - Atatürk İlkeleri (Laiklik, Devletçilik, Devrimcilik)', 'Atatürk İlkeleri ve İnkılâp Tarihi', 'SECOND', 'TURKISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 3, 14, 'Ders Tanıtımı, Veritabanı Sistemleri | Veri Modelleri, Varlık Bağıntı Modeli | Varlık Bağıntı Modeli Uygulamaları | İlişkisel Veri Modeli | Genişletilmiş Varlık Bağıntı Modeli, İlişkisel Cebir | Yapısal Sorgulama Dili (SQL), Temel SQL(DML) | Yapısal SQL Komutları (DDL) | İleri SQL | Ara Sınav | İleri SQL | SQL Programlama | Normalizasyon, Başarım İyileştirme | Proje Sunumları | Veritabanı Güvenliği, Diğer Veritabanı Modelleri', 'Veritabanı Yönetim Sistemleri', 'SECOND', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 3, 15, 'Ders Tanıtımı & Giriş | Logic | Kümeler, Fonksiyonlar | Diziler & Seriler | İspatlar | Tümevarım & Özyineleme | Sayma & Bağıntı | Yıl İçi Sınavı | Graflar | Graflar | Ağaçlar | Eşleme | Eşleme | Kriptoloji', 'Ayrık Matematik', 'SECOND', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 3, 16, 'Giriş | UML ile Modelleme | UML ile Modelleme | UML ile Modelleme | Gereksinimleri Anlama | Gereksinimleri Anlama | Analiz | Analiz | Sistem Tasarımı | Sistem Tasarımı | Nesne Tasarımı | Nesne Tasarımı | Gerçekleştirim | Test', 'Nesne Yönelimli Analiz ve Tasarım', 'SECOND', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 3, 17, '.Net ve MVC''ye genel bakış | Razor, ViewBag, ViewData, TempData | Formlar | Tag Helpers, ViewComponent | Partial View, Layout, Section | Model Binding | EF Core | EF Core | Validation | ASP. Net Core Uygulamaları | ASP. Net Core Uygulamaları | ASP. Net Core Uygulamaları | ASP. Net Core Uygulamaları | Proje Sunumları', 'Web Programlama', 'SECOND', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 1, 3, 18, 'Giriş, veri tipleri, fonksiyonlar, C++ derleme, işaretçiler | C++ sınıflar ve nesneler, diziler, öz yinelemeli algoritmalar | Arama ve Sıralama Algoritmaları | Liste soyut veri tipi, Dizi tabanlı gerçekleştirme | Bağlı listeler, Tek yönlü bağlı listeler | Çift yönlü bağlı listeler, Dairesel bağlı listeler | Yığıt soyut veri tipi ve gerçekleştirilmesi | Kuyruk soyut veri tipi ve gerçekleştirilmesi | Ağaç soyut veri tipi, ikili ağaçlar, ikili arama ağacı | İkili arama ağacı örnekleri | Heap ağacı, heap sıralama | Dengeli ikili ağaçlar, AVL ağaçları | Hash tabloları, Map | Python veri yapıları', 'Veri Yapıları ve Algoritmalar', 'SECOND', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (3, 1, 1, 19, 'Yapay Zekaya Giriş | Yapay Zeka Türleri ve Algoritmaları | Üretken Yapay Zeka ve Temel Kavramlar | Üretken Yapay Zeka ile Prompt Mühendisliği | ÜYZ Uygulamaları | Etik ve Sorumlu Kullanım | Toplumsal ve Ekonomik Etkiler | Güncel YZ Gelişmeleri ve Gelecek Beklentileri | Kısa Sınav | Proje Sunumları ve Değerlendirme | Proje Sunumları ve Değerlendirme | Proje Sunumları ve Değerlendirme | Proje Sunumları ve Değerlendirme | Proje Sunumları ve Değerlendirme', 'Yapay Zeka ve Üretkenlik (Seçmeli Ders)', 'SECOND', 'TURKISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 3, 21, 'Giriş (bilgisayar teknolojileri, programların çalıştırılması, bilgisayar mimarisinin tanımı) | Bilgisayarların performansı | Boole cebri lojik ifadelerin sadeleştirilmesi, | MIPS komut seti mimarisine giriş | Sayı sistemleri, sayıların temsil edilmesi | Yönergeler: Komut seti yapısı | Yönergeler: Mantıksal işlemler | Yönergeler: Kontrol, transfer ve karşılaştırma işlemleri | Yönergeler: Fonksiyonlar | Yönergeler: karakter karaktarlarının temsili | Programların makine diline çevrilmesi ve başlatılması | aritmetik işlemler | Kayan noktalı sayılar | Proje çalışması', 'Sayısal Tasarım ve Bilgisayar Mimarisi', 'SECOND', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 22, 'Bilgisayar sistemlerinin yapısı ve işletim sistemleri tanıtımı | İşletim sistemi alt birimleri | Proses yapısı ve komut istemcisi (kabuk) | İş parçacığı (thread) mimarisi proses ile kıyaslanması | Proses veri yapıları ve yönetimi | Prosesler arası senkronizasyon ve iletişim araçları | Prosesler ile ilgili uygulama (semafor, kilit vb.) | CPU planlama algoritmaları | Kilitlenmeler ve çözümleri | Bellek yönetimi | Sayfalama ve segmentasyon | Sanal bellek | Dosya sistemi, erişim ve koruma mekanizmaları | Giriş/çıkış sistemi, disk planlaması ve yönetimi', 'İşletim Sistemleri', 'SECOND', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 23, 'Dersin işleyişi, bilgi ve yönetim sistemlerinin mimari yapıları | Veritabanı sunucuları, SQL, veritabanı erişim örnekleri (JDBC, ODBC), soket bağlantısı, veritabanı tasarım prensipleri | Form tabanlı sistemlerin genel özellikleri, İstemci-sunucu (iki iskeleli) mimari uygulama geliştirme (JavaFx). | HTTP protokolü ve protokolün desteklediği metotlar. REST mimarisi ve MVC tasarım deseni | Nesnelerin veritabanına haritalanması: ORM (Object Relational Mapping) | Model-View-Controller tasarım deseni, veritabanı önce yaklaşımı | Kod önce yaklaşımı, Bootstrap CSS framework ile entegrasyon | Web güvenliği: Authentication ve authorization | Cookie temelli güvenlik uygulamaları, token temelli güvenlik uygulamaları (JWT) | Swagger ile REST API dokümantasyonu ve REST sistemlerde istisna ve hata yönetimi | REST sistemlerde dosya yükleme ve indirme, doküman sunucusu. | REST tabanlı bilgi sistemlerinde PDF, Excel raporların üretilmesi (Jasper Report veya JS Report kullanımı) | Mikroservis mimarilerin temel özellikleri, REST API ile mikroservis uygulama geliştirme (Feing client) | Proje çalışmalarının sunulması', 'Dağıtık Bilgi ve Yönetim Sistemleri', 'SECOND', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 3, 24, 'Yazılım Testine Giriş | Yazılım Testine Giriş | Doğrulama ve Onaylama | Test Stratejileri | Test Stratejileri | Yazılım Test Teknikleri ve Araçları | Yazılım Test Teknikleri ve Araçları | Yazılım Test Teknikleri ve Araçları | Yazılım Test Teknikleri ve Araçları | Yazılım Test Teknikleri ve Araçları | Yazılım Kalite Ölçütleri | İdame ve Konfigürasyon Yönetimi | Günümüzdeki Uygulamalar, Eğilimler, ve Zorluklar | Günümüzdeki Uygulamalar, Eğilimler, ve Zorluklar', 'Yazılım Doğrulama ve Onaylama', 'SECOND', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 3, 25, 'Yazılımların Güvenliği temel kavramları | Yazılım Güvenliği Prensipleri, Yazılım Güvenliğini Sağlama Yöntemleri | Güvenli yazılım geliştirme yaşam döngüsü | Güvenli Yazılım Geliştirme Olgunluk Modelleri, Web Uygulamalarının Temelleri ve Özellikleri | Güvenli Yazılım Geliştirme Olgunluk Modelleri, Web Uygulamalarının Temelleri ve Özellikleri | INJECTION ATTACK | INJECTION ATTACK | Ara Sınav | Cross Site Scripting (XSS) | Cross Site Request Forgery(CSRF) | Server Side Request Forgery(SSRF) | Cross Origin Resource Sharing (CORS) | Proje Çalışması | Proje Çalışması', 'Güvenli Yazılım Geliştirme', 'SECOND', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 26, 'Introduction to Course, Basic Definitions, Project Life Cycle | Introduction to Project Management, Documentation, Github & Jira & Confluence | Time Management | Estimation Techniques | Cost Management, Analyzing a Sample Project (in-class activity) | Risk Management | Software Process Models | Midterm | Requirements Specification & Analysis, Design, Implementation | Testing, Quality Management, Evolution & Configuration Management | Agile Approaches | Scrum & Kanban, Kanban Game (in-class activity) | People and Communication Management, Project Closure | Student Project Presentations', 'Yazılım Proje Yönetimi', 'THIRD', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 27, 'Büyük veriye giriş, temel bilgiler, data visualization | R ile veri analizi ve modelleme | Makine öğrenmesi: doğrusal regresyon, kümeleme ve sınıflandırma | Hadoop mimari özellikleri, HDFS dağıtık dosyalama sistemi, MapReduce programlama modeli | Apache-Yarn resource manager | Apache-Spark mimari özellikleri ve Spark ile dağıtık paralel hesaplama | Apache-Cassandra ile NoSQL uygulamaları, CAP ile ACID karşılaştırma | Spark-Cassandra ile web tabanlı uygulama geliştirme | Apache Kafka mimarisi, kurulumu ve uygulama geliştirme | Data pipeline uygulaması: Kafka-Spark-Cassandra | Apache-HBase mimari özellikleri ve NoSQL uygulamlar, Cassandra ile kıyaslama | Data warehousing ve ETL, Apache Hive | Apache NiFi, APache Sqoop data warehousing | Apache Flume ile sosyal medya uygulamalarından data çekme uygulamaları', 'Büyük Veri', 'THIRD', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 28, 'Bilgisayar ağlarına giriş | İnternet ve OSI modeli | Fiziksel ve veri katmanı | Ağ katmanı | IP protokolü | Yönlendirme algoritmaları | Taşıma katmanı (TCP, UDP) | Taşıma katmanı (tıkanıklık kontrolü) | Uygulama katmanı seviyesi protokoller | Ağ paketi yakalama | libpcap ile paket yakalama projesi | Socket programlama | Socket programlama | VOIP, multimedia, video', 'Bilgisayar Ağları', 'THIRD', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 29, 'Sistem yazılımlarında C dili kullanımı, yaygın olarak kullanılan yöntemler (conventions). | Program derleme ve bağlama (link) işlemleri. Makefile oluşturma. Hazır kütüphanelerin kullanımı. | Sistem çağrıları ve C kütüphaneleri ile performans karşılaştırmaları. | Dosya sistemleri, kısayol (link) ve dizin dosyaları. | Yaygın kullanılan sistem çağrıları ile uygulama geliştirme (stat, opendir, readdir/closedir kullanımı). | Diğer sistem çağrılarının analizi ve uygulamalarda kullanımı. | Kabuk programlama (shell programming) ve yeniden yönlendirme (redirection). | Sinyaller (signals), fork ve exec çağrılarının kullanımı | Simgesel dilde programlama - 1 (assembler): Giriş ve lokal değişkenler | Simgesel dilde programlama - 2 (assembler): Alt programlar (procedures) ve saklayıcı kopyalama (register spilling) | Simgesel dilde programlama - 3 (assembler): Adres değişkenleri (pointers) | Simgesel dilde programlama - 4 (assembler): Dallanma ve koşullu dallanma | Paralel programlama (Threads) | Paralel programlama: Sunucu istemci modelinde programlama', 'Sistem Programlama', 'THIRD', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 30, 'Tasarım Desenlerine Giriş | Tasarım Desenlerine Giriş | Yaratımsal Tasarım Desenleri | Yaratımsal Tasarım Desenleri | Yaratımsal Tasarım Desenleri | Yapısal Tasarım Desenleri | Yapısal Tasarım Desenleri | Yapısal Tasarım Desenleri | Davranışsal Tasarım Desenleri | Davranışsal Tasarım Desenleri | Davranışsal Tasarım Desenleri | Reaktif ve Eş Zamanlı Desenler | Reaktif ve Eş Zamanlı Desenler | Deyimler ve Anti Desenler', 'Tasarım Desenleri', 'THIRD', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 31, 'Introduction | Propositional logic | Predicate logic and quantifiers | Hoare Logic, weakest preconditions and strongest postconditions | Recursion and terminations, inductive data types | Lemmas and proofs | List proofs, sorting algorithms | Midterm exam | Abstraction and modules | Invariants for data structures | Loop invariants | Specifications for recursive and iterative Programs | Specifications for Objects | Specifications for Objects', 'Yazılım Mühendisliğinde Biçimsel Yöntemler', 'THIRD', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (6, 0, 3, 32, 'Algoritmalara giriş, ayrık matematik, veri yapıları, asimtotik notasyonlar, algoritma etkinliği | En iyi, en kötü ve ortalama zaman karmaşıklığı analizleri | Brute Force (Kaba Kuvvet) ve Algoritmaları: Selection Sort, Bubble Sort | Alan Karmaşıklığı | Divide and Conquer (Böl ve Yönet) ve Algoritmaları: Özyinelemeli Algoritmalar, Merge Sort, Quick Sort | Decrease and Conquer (Azalt ve Yönet) ve Algoritmaları: Insertion Sort | Dinamik Programlama - Böl ve Yönet: Fibonacci Serisi, Binom Sabitleri | Dinamik Programlama: En Uzun Alt Katar Problemi, Matris Çarpımı | Dinamik Programlama: En Kısa Yol Problemi, Sırt Çantası Problemi | Greedy Approach (Aç Gözlü Yaklaşım): Sırt Çantası Problemi, En Kısa Yol Problemi | Greedy Approach (Aç Gözlü Yaklaşım): Prim, Kruskal Algoritmaları | Transform and Conquer (Dönüştür ve Yönet): Mod Değeri Hesabı | Transform and Conquer (Dönüştür ve Yönet): İkili Ağaçlar, Denge ve AVL Ağaçları, Heap Sort | Hesaplama Teorisi: Hanoi Kuleleri, Karmaşıklık ve Hesaplanabilirlik Teorisi, NP-Tam, P, NP-Hard Problemler', 'Algoritma Analizi ve Tasarımı', 'THIRD', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (6, 0, 3, 33, 'Yapay zekaya giriş | Sezgisel problem çözme | Oyunlarda yapay zeka | Öğrenme metotları | Yapay sinir ağları | Evrişimsel sinir ağları | Özyinelemeli sinir ağları | Derin inanç ağları | Genetik algoritmalar | Bulanık mantık | Uzman sistemler | Yapay zekada optimizasyon algoritmaları | Öğrenci sunumları ve uygulamalar | Öğrenci sunumları ve uygulamalar', 'Yapay Zeka Temelleri', 'THIRD', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (6, 0, 3, 34, 'Mobil Uygulama Geliştirmeye Giriş | Mobil Uygulama Geliştirme Temelleri | Mobil Uygulama Geliştirme Temelleri | Mobil Uygulama Geliştirme Temelleri | Yerleşim Düzeni | Tasarım ve Tema | Etkileşim | Varlıklar ve Medya | Navigasyon ve Yönlendirme | Erişilebilirlik ve Uluslarasılaştırma | Veri ve Arka Uç | Uygulama Mimarisi | Test ve Hata Ayıklama | Dağıtım', 'Mobil Uygulama Geliştirme', 'THIRD', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 35, 'Yazılım yaşam döngüsü. Yazılım build araçları: Make, Ant, Maven, Gradle, Msbuild vs. | Şelale ve çevik yazılım geliştirme modelleri. DevOps fazları: Plan, code, build, test, integrate, deploy, operate ve monitor. | Versiyon kontrol sistemleri (Git) ve grup halinde yazılım geliştirme. | Bulut sistem ile yazılımların yayınlanması (publish). Basit dosya transferi (FTP) ile yazılım yayınlama. Web sunucusu (Nginx) konfigürasyonu. | Sanallaştırma ve konteyner teknolojileri (Docker). Dockerfile ile yazılımların konteynera konulması. | Konteyner hub kullanımı (Docker-Hub). Konteyner hub (Docker-Hub) üzerinden yazılım dağıtımı. Bulut üzerinde yayınlama. | Docker compose ile çok sayıda konteynerin organizasyonu ve koordinasyonu. | GitHub ile yazılım oluşturma (build) ve akış kontrolu (flow). | Sürekli teslimat (Continuous Delivery). | Sürekli dağıtım (Continuous Deployment). | Jenkins sunucusu ile yazılım yayınlama süreçlerinin otomatikleştirilmesi. Sürekli entegrasyon (Continuous Integration with Jenkins). | Lokal bilgisayarda veya bulut üzerinde Kubernetes küme bilgisayar oluşturma ve konteyner yayınlama. | Bulut üzerinde Kubernetes ile sürekli performans izleme. | Proje çalışmalarının değerlendirilmesi ve tartışma.', 'Yazılım Geliştirme Süreçleri (Devops)', 'THIRD', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 2, 0, 36, 'Proje çalışması konusunun belirlenmesi | Proje çalışmasının kapsadığı alt konuları belirleme | Kaynak taraması | Kaynak taraması | Kaynak taraması | Sistemin tasarımı | Sistemin planlanması | Analiz | Analiz | Değerlendirme | Değerlendirme | Belgeleme | Belgeleme | Düzeltmeler ve teslim', 'Yazılım Mühendisliği Tasarımı', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 37, 'Introduction, Artificial Intelligence, Machine Learning and Deep Learning | Mathematical background, tensor operations, activation functions | Gradient descent and variants, loss functions | Feedforward networks and training, Keras deep learning library | Data preprocessing, regularization methods | Convolutional neural networks | Transfer learning | Text processing, embedding layers | Sequence processing, Recurrent neural networks (RNN) | Simple RNN,LSTM, GRU | Keras functional API | Generative deep learning | Contemporary deep learning topics | Presentations', 'Derin Öğrenme ve Uygulamaları (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 38, 'Sayısal analize giriş , sayısal yöntemler, algoritma mantığı | Matrisler ve matris işlemleri | Matrisler ve matris işlemleri | Doğrusal denklem sistemleri çözüm yöntemleri | Doğrusal olmayan denklem sistemleri çözüm yöntemleri | Eğri uydurma, aradeğer ve dış değer bulma yöntemleri | Eğri uydurma, aradeğer ve dış değer bulma yöntemleri | Yıl İçi Sınavı | Sayısal integral yöntemleri | Sayısal integral yöntemleri | Sayısal türev yöntemleri | Uygulama | Uygulama | Uygulama', 'Sayısal Analiz Teknikleri ve Uygulamaları (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 39, 'İnsan-Bilgisayar Etkileşimine Giriş | HCI Uygulama Alanı I - Sanal Gerçeklik | HCI Uygulama Alanı II - Arttırılmış Gerçeklik | HCI Uygulama Alanı III - Robotik | HCI Uygulama Alanı IV - Nesnelerin Interneti | HCI Uygulama Alanı V - Giyilebilir Teknolojileri | HCI Uygulama Alanı VI - Konuşma Tanıma ve Arayüzleri | Yıliçi Sınavı | HCI Uygulama Alanı VII - Beyin/Bilgisayar Arayüzleri | HCI Uygulama Alanı VIII - Bilgisayar Oyunları | HCI Uygulama Alanı IX - Görüntü İşleme ve Bilgisayar Görmesi | HCI Uygulama Alanı X - Derin Öğrenme ve Makine Öğrenmesi | HCI Uygulama Alanı XI - Büyük Veri İle Çalışma | Kötü Tasarımlar', 'İnsan Bilgisayar Etkileşimi (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 40, 'Ders Tanıtımı & Giriş | Bilgisayar Grafiği Donanım Bileşenleri | Temel Bilgisayar Grafiği Matematiği | 2B/3B Dönüşümler | 2B/3B Dönüşümler | Projeksiyon | Sahneleme | Işık ve Gölge | Kırpma | Renk | Etkileşimli Bilgisayar Grafiği Uygulama Alanları | Etkileşimli Bilgisayar Grafiği Uygulama Alanları | Etkileşimli Bilgisayar Grafiği Uygulama Alanları | Etkileşimli Bilgisayar Grafiği Uygulama Alanları', 'Etkileşimli Bilgisayar Grafiğine Giriş (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (4, 0, 4, 1, 'A. Dersin amacı ve işleyişi, dilin tanımı ve insan hayatındaki yeri B. Konuşma dili ile yazı dili arasındaki farklar. | A. Dilin özellikleri ve dilin yapısını kavrama. Okuma ve anlama yöntemleri B. Noktalama işaretleri | A. Dünya dilleri arasında Türkçe; lehçe, şive ve ağız arasındaki farklar B. Dil-düşünce ilişkisini kavrama, eleştirel düşünme. Noktalama işaretleri | A. Belli başlı Türkçe eserlerin değerlendirilmesi B. Yazım kuralları | A. Örneklerle Türkçenin ses özellikleri B. Kültürün değişen ve değişmeyen unsurları | A. Türkçede sözcük yapısının incelenmesi B. Yazı türlerinden Şiir ve şiir incelemesi C. Yazı için ön hazırlıklar D. Form yazıları: dilekçe, tutanak, rapor... | A. Sözcük Türleri B. Roman ve hikâye türleri. Edebiyatta kurgu-yaşantı ayrımı. C. Sözlük kullanımı | A. Söz öbekleri B. Klasik kurmaca türler C. Ödev, proje hazırlama D. Yazılı ve Görsel Medyada Dil Yanlışları | A. Türkçede cümle yapısı ve cümle türleri B. Kullanmalık Metinler: Tiyatro, senaryo C. Bilimsel yazmanın ilkeleri. Yazmada plan, iyi bir plan nasıl yapılır? | A. Cümle üstü dil yapıları: paragraf ve metin B. İşlevsel Türler: Makale-Eleştiri. Eleştiride yöntem sorunu. C. İletişim kazaları | A. Semantik bilgisi B. İşlevsel Türler: Deneme - Fıkra-Gazete Köşe yazısı-Söyleşi C. Paragraf yazımı; paragraf türleri ve özellikleri | A. Söz sanatları ve Türkçenin söz varlığı B. İşlevsel Türler: Mektup, Gezi Yaazısı, Anı, Günlük.C. Dil Yanlışları (Anlatım Bozuklukları). | A. Türkçenin güncel sorunları B. Diksiyonda dikkat edilmesi gereken noktalar C. Bilimsel yazılar | Genel tekrar', 'Türk Dili', 'FIRST', 'TURKISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 41, 'Dersin tanımı, Kriptoloji bilimi ve temel bilgiler | Klasik şifreleme yöntemleri | Matematiksel alt yapı (euclid algoritması, modüler artimetik, fermat teoremi vb.) | Rasgele sayı üreteçleri ve Rassallık testleri | Simetrik şifreleme (Blok şifreleme- Rijndael Feistel mimarisi ) | Simetrik şifreleme (DES-AES) | Akan Şifreleme algoritmaları ve uygulamaları (RC-4) | Vize | Asimetrik şifreleme- RSA / El-Gamal | Eliptik Eğri Şifreleme algoritması | Anahtar değişim yönetimi- (Diffie Helman) | Özetleme Fonksiyonları (Hash Function) | Kriptoloji algoritmaları ile şifreleme uygulamaları (RSA-AES) | Kriptografik protokoller(SSL, IPSec, Kerberos)', 'Kriptolojiye Giriş (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 42, 'Dijital görüntü işlemeye giriş | Piksel işlemleri | Filtreleme | Kenar ve kontor bulma | Bölütleme | Morfolojik işlemler | Renkli görüntü işleme | Anahtar nokta tespiti | Özellik bazlı görüntü eşleştirme | Şablon esleştirme ve nesne tespiti | Makine Öğrenmesi ve görüntü işleme | İleri seviye konular (Hareket tespiti, nesne takip...) | Proje sunumları | Proje sunumları', 'Dijital Görüntü İşleme (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 43, 'Paralel sistemler ve paralel programlamaya giriş | Paralel performans, Amdahl kanunu | Sıkı bağlı ve gevşek bağlı paralel sistemler | Görev dağılımı ve kritik yol | Çok çekirdekli işlemciler | Thread temelli paralel programlama, thread havuzu | OpenMP ile derleyici destekli paralel programlama | Cilk ile recursive paralel programlama | GPU programlama | Dağıtık paralel sistemler | MPI (Message Passing Interface) ile dağıtık programlama | Paralel yazılımlarda olayların izlenmesi ve performans hatalarının ayıklanması | Projelerin sunumu ve değerlendirilmesi | Projelerin sunumu ve değerlendirilmesi', 'Paralel ve Dağıtık Hesaplama (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 44, 'Sanallaştırma: Tanım ve tekniklerinin tanıtımı | Sanallaştırma için donanımsal ve yazılımsal destekler | Konteyner teknolojileri: Docker | Konteyner yönetimi: Kubernetes | Oracle VirtualBox | VMWare | Citrix XenServer | Emülatörler | Bulut bilişim modelleri | Servis olarak yazılım (SaaS) | Servis olarak platform (PaaS) | Servis olarak altyapı (IaaS) | Ders kapsamında yapılan projelerin sunumu. | Ders kapsamında yapılan projelerin sunumu.', 'Sanallaştırma ve Bulut Bilişim (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 45, 'Veri madenciliğine giriş | Veri türleri, veri kalitesi, veri benzerliği ve veriler arası ilişkiler | Veri ön işlme | Sınıflandırma temelleri ve algoritmaları | Sınıflandırma: Karar ağaçları | Sınıflandırma: KNN algoritması | Sınıflandırma: SVM algoritması | Birliktelik analizi | Kümeleme | Resresyon analizi | Veri görselleştirme | Anamoli tespiti | Uygulamalar | Uygulamalar', 'Veri Madenciliği (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 46, ' |  |  |  |  |  |  |  |  |  |  |  |  | ', 'Veri Analitiği (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 47, 'Doğal dil işlemeye genel bakış | Doğal dil işlemenin pratikteki zorlukları | Dilbilimsel temeller ve bilgi düzeyleri: kelimeler, biçimbilim, sözlükler, sözdizimi, semantik | Temel metin işleme, biçimbilimsel analiz, edit distance algoritması | Doğrusal metin sınıflandırması: Naive Bayes, SVM, Perceptron, Lojistik Regression | Doğrusal olmayan sınıflandırma: sinir ağları | Metin sınıflandırmasının uygulamaları: duygu analizi | N-gramlar, İstatistiksel dil modelleri | Sinir ağı tabanlı dil modelleri | Dizi etiketleme: gizli markov modelleri | Dizi etiketleme: sinir modelleri | Dizi etiketleme uygulamaları: sözcük türü etiketleme, varlık ismi tanıma | Vektör semantiği ve gösterilimleri | Proje sunumları', 'Doğal Dil İşleme (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'FALL');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 48, 'Giriş | Gerçek Zamanlı Sistemlere Giriş | Gerçek Zamanlı İşletim Sistemleri | Gerçek Zamanlı İşletim Sistemleri | Planlama Şemaları | Planlama Şemaları | Planlama Şemaları | Analiz Metodları | Analiz Metodları | Gerçek Zamanlı Sistemleri Programlama | Gerçek Zamanlı Sistemleri Programlama | Gerçek Zamanlı Sistemleri Programlama | Gerçek Zamanlı Sistemleri Programlama | Karışık-Kritik Sistemler', 'Gerçek Zamanlı Sistemler (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 49, 'Siber Güvenliğe Giriş | Kriptolojiye Giriş | AAA (kimlik doğrulama, yetkilendirme, muhasebe) | Ağ Güvenliği (Katman 2, katman 3) | Ağ Güvenliği (Katman 7) | Web Güvenliği | Zararlı Yazılım Analizi | Ara Sınav | Sosyal Mühendislik | Kablosuz Ağlar ve IoT Güvenliği | Sızma Testleri | Sızma Testleri | Bilgi Güvenliği Standartları | Bilgi Güvenliği Standartları', 'Bilgi Güvenliğine Giriş (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 50, 'Fundamental concepts | Performance limits and profiling | Performance limits and profiling | Data design | Parallel algorithms and patterns | Vectorization | OpenMP: Open Multi-Processing | OpenMP: Open Multi-Processing | MPI: Message Passing Interface | GPU architectures and concepts | GPU programming model | High performance computing systems | Batch schedulers | Presentations', 'Yüksek Başarımlı Hesaplama (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 51, 'Veri iletişimine giriş, temel kavramlar | Ağ modeli | Fiziksel katman ve sinyaller | İletim ortamları ve bozulmalar | Sayısal-Sayısal kodlama teknikleri | Sayısal-Analog kodlama teknikleri | FDM,TDM | Veri bağı katmanı | Hata tespit ve düzeltme yöntemleri | Hata tespit ve düzeltme yöntemleri | Ağ katmanı | Yönlendirme protokolleri | Taşıma katmanı | Uygulama katmanı', 'Veri İletişimi ve Bilgisayar Ağları (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 52, 'Introduction, history of gamification | Games and Play | Game Thinking | Game Elements | Gamification as motivational design | Behaviorism in gamification, Reward structures | Reward schedules,Limits of behaviorism | Midterm exam | Design Framework, Business objectives/target behaviors | Players, Activity loops | Design Choices | Enterprise applications | Workplace motivations | Social good applications', 'Oyunlaştırma (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 53, ' |  |  |  |  |  |  |  |  |  |  |  |  | ', 'Yazılım Güvenliği ve Yazılım Kalite Güvencesi (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 54, 'Dersin tanımı, Kriptoloji bilimi ve uygulamaları | Matematiksel teoremler | Simetrik/asimetrik şifreleme algoritmaları /özetleme fonksiyonları/anahtar değişim yöntemleri | SSL/TLS | IPsec | SSH (Secure Shell) | Authentication Protocols | Vize | PGP, Kerberos | Anahtar Değişim Protokolleri (IKE or IKEv2) | Kablosuz Ağ Güvenliği | Electronik Mail Güvenliği | Ağ Erişim ve Bulut Güvenliği | Proje', 'İnternet Güvenlik Protokolleri (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 55, 'Büyük dil modellerinin yapıtaşları | Sinir ağı modelleri ve transformer mimarisi | Transformer ile eğitim | Maskeli dil modelleri | İnce ayar (fine-tuning) | Az veri ile çalışma | Komut verme | Bağlamdan öğrenme | Büyük dil modellerinin değerlendirilmesi | Büyük dil modellerinde anımsama | Kod tabanlı büyük dil modelleri | Büyük dil modellerinde açıklanabilirlik ve yorumlanabilirlik | Büyük dil modelleri uygulamalarının operasyonları (LLMOps) | Öğrenci Sunumları', 'Büyük Dil Modellerine Giriş (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 56, ' |  |  |  |  |  |  |  |  |  |  |  |  | ', 'Kuantum Hesaplama ve Uygulamaları (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 57, ' |  |  |  |  |  |  |  |  |  |  |  |  | ', 'Bulut Bilişime Giriş (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'SPRING');
INSERT INTO public.home_course (ects, practical_hours, theoretical_hours, home_course_id, description, course_name, education_year, language, semester) VALUES (5, 0, 3, 58, ' |  |  |  |  |  |  |  |  |  |  |  |  | ', 'Blockchain Teknolojileri (Bf-Teknik Seçmeli)', 'FOURTH', 'ENGLISH', 'SPRING');


--
-- Name: home_course_home_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.home_course_home_course_id_seq', 58, true);


--
-- PostgreSQL database dump complete
--

