spring.application.name=summer

server.port=8090

# Show SQL statements in the console (optional, for debugging)
spring.jpa.show-sql=true

# Format SQL output (optional, for readability)
spring.jpa.properties.hibernate.format_sql=true

# Enable Hibernate to automatically update schema based on entity classes
spring.jpa.hibernate.ddl-auto=update

#server.port=8090

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/bitirmedb
spring.datasource.username=postgres
spring.datasource.password=postgres

# Whitelabel closed
server.error.whitelabel.enabled=false

# Details on exception messages
server.error.include-message=always
server.error.include-binding-errors=always

# Open 404 Exception
spring.web.resources.add-mappings=false
