spring.application.name=summer

server.port=8090

# Show SQL statements in the console (optional, for debugging)
spring.jpa.show-sql=true

# Format SQL output (optional, for readability)
spring.jpa.properties.hibernate.format_sql=true

# Enable Hibernate to automatically update schema based on entity classes
spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:summerdb}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:ss2025%}

# Whitelabel closed
server.error.whitelabel.enabled=false

# Details on exception messages
server.error.include-message=always
server.error.include-binding-errors=always

# Open 404 Exception
spring.web.resources.add-mappings=false
